/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        mavenLocal()
        //add the dependency to Reflekt Maven repository
        maven(url = uri("https://packages.jetbrains.team/maven/p/reflekt/reflekt"))
        gradlePluginPortal()
    }
}

rootProject.name = "KC-UHC"
