admins: []
discord:
  #######################################################
  #                       WARNING                       #
  #                                                     #
  #    Do not change the below value or share it with   #
  #  anyone! This is a unique ID generated to identify  #
  #  your server with the robot. Giving this id out may #
  #   cause discord integration to not work correctly   #
  #######################################################
  serverId: ''
  # Enables discord integration
  useDiscord: false
  # The host of the redis server
  botHost: 'localhost'
  # The redis server's port
  botPort: 6379
  # A password for the redis server
  botPassword: ''
  inviteUrl: ''
episodes:
  # Enable episode markers
  use: true
  # The duration in minutes of each episode
  duration: 20